"""Regenerate src/domains.js from CIC's "Fields in Excel" workbook.

Usage:
    python tools/build_domains.py "path/to/Fields in Excel v1.7.xlsx"

The cell ranges below follow the layout of v1.7. If CIC ships a new version,
check that the lookup tables still sit in the same places before trusting
the output.
"""
import json
import sys
import warnings
from pathlib import Path

import openpyxl

warnings.filterwarnings("ignore", category=UserWarning)

# name: (sheet, code column, description column, first row, last row or None = until blank)
BLOCKS = {
    "Title": ("ID - Individual", "A", "B", 3, 13),
    "Country": ("ID - Individual", "A", "B", 17, None),
    "Gender": ("ID - Individual", "E", "F", 3, 4),
    "CivilStatus": ("ID - Individual", "E", "F", 10, 13),
    "IdentificationType": ("ID - Individual", "E", "F", 18, 27),
    "OccupationStatus": ("ID - Individual", "E", "F", 32, 40),
    "YesNo": ("ID - Individual", "I", "J", 3, 4),
    "HouseOwnerLessee": ("ID - Individual", "I", "J", 10, 13),
    "IDType": ("ID - Individual", "I", "J", 18, 47),
    "AddressTypeIndividual": ("ID - Individual", "L", "M", 2, 3),
    "ContactType": ("ID - Individual", "L", "M", 10, 18),
    "AnnualMonthly": ("ID - Individual", "L", "M", 23, 24),
    "Currency": ("ID - Individual", "L", "M", 28, None),
    "PSIC": ("ID - Individual", "O", "P", 3, None),
    "PSOC": ("ID - Individual", "R", "S", 3, None),
    "LegalForm": ("BD - Business Data", "A", "B", 9, 25),
    "FirmSize": ("BD - Business Data", "E", "F", 3, 6),
    "AddressTypeCompany": ("BD - Business Data", "E", "F", 10, 11),
    "Role": ("CI - Installment Contract", "A", "B", 3, 5),
    "ContractPhase": ("CI - Installment Contract", "D", "E", 3, 8),
    "ContractTypeInstallment": ("CI - Installment Contract", "G", "H", 3, 33),
    "ContractStatusInstallment": ("CI - Installment Contract", "A", "B", 12, 26),
    "OverdueDays": ("CI - Installment Contract", "D", "E", 13, 20),
    "NewUsed": ("CI - Installment Contract", "D", "E", 24, 25),
    "ReorganizedCredit": ("CI - Installment Contract", "A", "B", 30, 32),
    "TransactionType": ("CI - Installment Contract", "A", "B", 36, 73),
    "InstallmentType": ("CI - Installment Contract", "D", "E", 36, 37),
    "GoodType": ("CI - Installment Contract", "D", "E", 42, 66),
    "PaymentMethod": ("CI - Installment Contract", "G", "H", 38, 45),
    "PaymentPeriodicity": ("CI - Installment Contract", "G", "H", 50, 61),
    "GuaranteeCustomerType": ("CN - Non-Installment", "A", "B", 3, 4),
    "Guarantees": ("CN - Non-Installment", "A", "B", 9, 44),
    "ContractStatusNonInstallment": ("CN - Non-Installment", "D", "E", 5, 16),
    "CreditPurpose": ("CN - Non-Installment", "D", "E", 20, 42),
    "ContractTypeNonInstallment": ("CN - Non-Installment", "G", "H", 3, 34),
    "ContractStatusCreditCard": ("CC- Credit Card ", "A", "B", 5, 24),
    "ContractTypeCreditCard": ("CC- Credit Card ", "E", "F", 3, 7),
    "CardPremium": ("CC- Credit Card ", "E", "F", 12, 13),
    "ContractTypeUtilities": ("UT- ServicesUtilities", "A", "B", 4, 13),
    "ContractStatusUtilities": ("UT- ServicesUtilities", "A", "B", 18, 22),
    "LiableFlag": ("UT- ServicesUtilities", "A", "B", 26, 27),
    "EventStatus": ("NE - Negative Events", "A", "B", 3, 4),
    "SubjectInfoType": ("NE - Negative Events", "A", "B", 9, 20),
    "CompanyRole": ("SL - Subject Link", "A", "B", 3, 10),
}


def text(v):
    if v is None:
        return ""
    if isinstance(v, float) and v.is_integer():
        v = int(v)
    return " ".join(str(v).split())


def read_block(wb, sheet, ccol, dcol, first, last):
    ws = wb[sheet]
    out = {}
    row = first
    end = last if last is not None else ws.max_row
    while row <= end:
        code = text(ws[f"{ccol}{row}"].value)
        desc = text(ws[f"{dcol}{row}"].value)
        if last is None and not code:
            break
        # Rows with a description but no code are sub-labels of the code above.
        if code and desc:
            out[code] = desc
        row += 1
    return out


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = Path(sys.argv[1])
    wb = openpyxl.load_workbook(src)
    domains = {name: read_block(wb, *spec) for name, spec in BLOCKS.items()}
    empty = [n for n, d in domains.items() if not d]
    if empty:
        sys.exit(f"No codes found for: {', '.join(empty)} - workbook layout changed?")

    out = Path(__file__).resolve().parent.parent / "src" / "domains.js"
    body = json.dumps(domains, ensure_ascii=False, separators=(",", ":"))
    out.write_text(
        f"// Generated by tools/build_domains.py from \"{src.name}\". Do not edit by hand.\n"
        "(function (root) {\n"
        f"  var DOMAINS = {body};\n"
        f"  var SOURCE = {json.dumps(src.name)};\n"
        "  var api = { DOMAINS: DOMAINS, SOURCE: SOURCE };\n"
        "  if (typeof module !== 'undefined' && module.exports) module.exports = api;\n"
        "  else root.CIC_DOMAINS = api;\n"
        "})(typeof globalThis !== 'undefined' ? globalThis : this);\n",
        encoding="utf-8",
    )
    for name, d in domains.items():
        print(f"{name:32s} {len(d):5d}")
    print(f"wrote {out} ({out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
